apiVersion: apps/v1
kind: Deployment
metadata:
  name: tombaugh-deployment
spec:
  selector:
    matchLabels:
      app: tombaugh-deployment
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: tombaugh-deployment
    spec:
      containers:
      - name: tombaugh
        image:  martinikola/tombaugh:latest
        env:
          - name: PORT
            value: "8181"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tombaugh-service
  labels:
    run: tombaugh-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80  # http://tombaugh:80
      protocol: TCP
      targetPort: 8181
  selector:
    app: tombaugh-deployment