apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: nginx-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80  # http://tombaugh:80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-deployment
